import { Project } from '@/types/project';

export const PROJECTS: Project[] = [
  {
    id: '1',
    slug: 'lumina-residence',
    title: 'Lumina Residence',
    subtitle: 'London, UK',
    description: 'A study in transparency and brutalist elegance. Lumina Residence uses floor-to-ceiling glass and raw concrete to create a dialogue between the internal sanctuary and the urban garden.',
    category: 'Residential',
    client: 'Private Owner',
    location: 'Mayfair, London',
    year: '2023',
    coverImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=2070&auto=format&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1600566753190-17f0bb2a6c3e?q=80&w=2070&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?q=80&w=2070&auto=format&fit=crop',
    ],
    featured: true,
    aspectRatio: 'portrait',
  },
  {
    id: '2',
    slug: 'monolith-gallery',
    title: 'Monolith Gallery',
    subtitle: 'Berlin, DE',
    description: 'An adaptive reuse of a former industrial warehouse. The Monolith Gallery preserves the rugged character of its past while introducing refined architectural elements for modern art displays.',
    category: 'Commercial',
    client: 'City Arts Collective',
    location: 'Mitte, Berlin',
    year: '2022',
    coverImage: 'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=2069&auto=format&fit=crop',
    images: [],
    aspectRatio: 'landscape',
  },
  {
    id: '3',
    slug: 'fjord-house',
    title: 'The Fjord House',
    subtitle: 'Oslo, NO',
    description: 'Perched on the edge of the Norwegian landscape, this timber-clad retreat celebrates the warmth of natural materials and the precision of Scandinavian craft.',
    category: 'Architecture',
    client: 'Nordic Escapes',
    location: 'Oslo, Norway',
    year: '2024',
    coverImage: 'https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?q=80&w=2035&auto=format&fit=crop',
    images: [],
    aspectRatio: 'portrait',
  },
  {
    id: '4',
    slug: 'solis-penthouse',
    title: 'Solis Penthouse',
    subtitle: 'Los Angeles, US',
    description: 'A high-altitude penthouse in the heart of Downtown LA, featuring an open-plan layout that prioritizes cinematic views and seamless entertaining.',
    category: 'Residential',
    client: 'Private Equity',
    location: 'Los Angeles, US',
    year: '2023',
    coverImage: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?q=80&w=2070&auto=format&fit=crop',
    images: [],
    aspectRatio: 'landscape',
  },
  {
    id: '5',
    slug: 'azure-retreat',
    title: 'Azure Boutique Resort',
    subtitle: 'Santorini, GR',
    description: 'Cliffside hospitality that redefines Mediterranean luxury through white-washed stone, private water elements, and endless horizons.',
    category: 'Hospitality',
    client: 'Azure Hotels',
    location: 'Santorini, Greece',
    year: '2024',
    coverImage: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=2070&auto=format&fit=crop',
    images: [],
    featured: true,
    aspectRatio: 'portrait',
  },
  {
    id: '6',
    slug: 'ethos-headquarters',
    title: 'Ethos HQ',
    subtitle: 'New York, US',
    description: 'A forward-thinking workspace that optimizes focus and collaboration through biophilic design and ergonomic spatial planning.',
    category: 'Commercial',
    client: 'Ethos Tech',
    location: 'Manhattan, New York',
    year: '2023',
    coverImage: 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?q=80&w=2000&auto=format&fit=crop',
    images: [],
    aspectRatio: 'landscape',
  },
];
